default:
  postgres:
    database: !ENV ${POSTGRES_DB}
    user: !ENV ${POSTGRES_USER}
    password: !ENV ${POSTGRES_PASSWORD}
    host: !ENV ${POSTGRES_HOST}
    port: !ENV ${POSTGRES_PORT}
  
  colorific:
    allowed_image_content_types:
      - image/jpeg
      - image/png
    http_client_retrying_max_attempts: 5
    http_client_retrying_wait_time: 3
    http_client_timeout: 30
    image_max_size_bytes: 5242880 # 5 Mb
    image_max_height: 5000
    image_max_width: 5000
    image_min_height: 50
    image_min_width: 50
    pool_exec_size: 2

test:
  postgres:
    database: !ENV ${POSTGRES_TEST_DB}
    user: !ENV ${POSTGRES_TEST_USER}
    password: !ENV ${POSTGRES_TEST_PASSWORD}
    host: !ENV ${POSTGRES_TEST_HOST}
    port: !ENV ${POSTGRES_TEST_PORT}

  colorific:
    http_client_retrying_max_attempts: 2
    http_client_retrying_wait_time: 0.5
    http_client_timeout: 1
    image_max_size_bytes: 1500000
    image_max_height: 1000
    image_max_width: 1000
    pool_exec_size: 1
