version: '3'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    restart: always

  backend:
    build: .
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.19
    restart: always
    depends_on:
      - backend
    volumes:
      - /var/run/colorific:/var/run/colorific
      - ./.logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist/client:/app
