version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: test
    steps:
      - checkout
      - restore_cache:
          key: colorific-{{ checksum "requirements/main.txt" }}
      - run:
          name: Create virtual environment
          command: test -d .venv || python -m venv .venv
      - run:
          name: Install requirements
          command: .venv/bin/pip install -r requirements/main.txt
      - save_cache:
          key: colorific-{{ checksum "requirements/main.txt" }}
          paths:
            - .venv
      - run:
          name: Run tests
          command: source .venv/bin/activate && make test
          environment:
            POSTGRES_TEST_USER: postgres
            POSTGRES_TEST_PASSWORD: test
            POSTGRES_TEST_DB: postgres
            POSTGRES_TEST_HOST: localhost
            POSTGRES_TEST_PORT: 5432
            OMP_NUM_THREADS: 1
            IMAGE_INDEXING: false
            CORS_ALLOW_ORIGIN: '*'

workflows:
  main:
    jobs:
      - build-and-test
