version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
        name: The First Step
        command: |
          python -c "assert 6 * 7 == 42"

workflows:
  main:
    jobs:
      - build-and-test