version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8
      - image: postgres:12
        environment:
          POSTGRES_USER: $POSTGRES_TEST_USER
          POSTGRES_PASSWORD: $POSTGRES_TEST_PASSWORD
          POSTGRES_DB: $POSTGRES_TEST_DB
          POSTGRES_HOST: $POSTGRES_TEST_HOST
          POSTGRES_PORT: $POSTGRES_TEST_PORT
    steps:
      - checkout
      - run:
          name: Run tests
          command: pytest

workflows:
  main:
    jobs:
      - build-and-test