"""Add color names

Revision ID: 261f29a1fe60
Revises: b64dc15f0fc2
Create Date: 2020-07-08 20:22:18.510054+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "261f29a1fe60"
down_revision = "b64dc15f0fc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image_color", sa.Column("name", sa.String(), nullable=True))
    op.add_column("image_color", sa.Column("name_distance", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image_color", "name_distance")
    op.drop_column("image_color", "name")
    # ### end Alembic commands ###
